## N05 Arrays and Matrics

Unlike Python, R has multi-dimensional arrays and a two dimensional matrix. These are intended for numeric operations.  Python provides many of the same features in the numpy package.

Like most things in R, these are created by using a function.

A matrix is created with the matrix function:

## matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,  dimnames = NULL)

Arguments

## data 	

an optional data vector (including a list or expression vector). Non-atomic classed R objects are coerced by as.vector and all attributes discarded.

## nrow 	

the desired number of rows.

## ncol 	

the desired number of columns.

## byrow 	

logical. If FALSE (the default) the matrix is filled by columns, otherwise the matrix is filled by rows.

## dimnames 	

A dimnames attribute for the matrix: NULL or a list of length 2 giving the row and column names respectively. An empty list is treated as NULL, and a list of length one as row names. The list can be named, and the list names will be used as names for the dimensions.

## x 	

an R object.

In [1]:
bob <- matrix(0,2,2)
bob
fred <- matrix(2.33,3,4)
fred


[,1] [,2]
[1,] 0    0   
[2,] 0    0

[,1] [,2] [,3] [,4]
[1,] 2.33 2.33 2.33 2.33
[2,] 2.33 2.33 2.33 2.33
[3,] 2.33 2.33 2.33 2.33

In the above example, the matrix has all elements initialized to the same values. This is often done when you desire to start with an empty matrix containing all zeros.

You can also initialize the matrix with more than one value in a vector.

In [2]:
jack <- matrix(c(1,2,3,4,5,6),2,3)
jack

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

The vector fills the columns from left to right

In [5]:
jack[1,1]
jack[1,3]

[1] 1

[1] 5

The matrix access is [row,col]. Like the rest of R, the first element is numbered 1, not 0 like python.

In [3]:
jill <- matrix(c(0,1),2,3)
jill

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 1    1    1

If the vector is short, then it is reused to fill the matrix.

In [4]:
jane <- matrix(c(0,1,2),2,3)
jane

[,1] [,2] [,3]
[1,] 0    2    1   
[2,] 1    0    2

The data doesn't have to fit the matrix exactly. It is just used until the matrix is filled.

In [7]:
ma <- matrix(1,2,2)
mb <- matrix(2,2,2)
ma
mb
ma*mb

[,1] [,2]
[1,] 1    1   
[2,] 1    1

[,1] [,2]
[1,] 2    2   
[2,] 2    2

[,1] [,2]
[1,] 2    2   
[2,] 2    2

Matrix addition is supported. The matrics need to have the same dimensions.

In [25]:
ma*mb

[,1] [,2]
[1,] 2    2   
[2,] 2    2

multiplication is element by element, like vectors, not matrix multiplication.

In [24]:
ma %*% mb

[,1] [,2]
[1,] 4    4   
[2,] 4    4

The %*% operator performs matrix multiplication


A matrix may be multiplied by a scalar (A single number). The scalar gets converted to a matrix, and then element by element multiplication is performed.

In [27]:
4*mb

[,1] [,2]
[1,] 8    8   
[2,] 8    8

Explain what happened in this box:

A scalar 4 is converted into a matrix of same dimension as of target matrix i.e 2*2 and each element of target matrix is multiplied by scalar number.

Download as a PDF, and submit on Canvas